# 应用服务 WEB 访问端口
server.port=8080

# 数据库配置
spring.datasource.url=jdbc:mysql://localhost:3306/apartmentsystem?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=520134
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# mybatis-plus配置
mybatis-plus.mapper-locations=classpath:mappers/*.xml
mybatis-plus.configuration.map-underscore-to-camel-case=false
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# redis配置
spring.redis.host=localhost
spring.redis.port=6379

# alipay配置
alipay.alipay-client.appId= 9021000138605307
alipay.alipay-client.privateKey= MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgzpdRgreqyGZlbZMbLmV6Uppm3Ca6pazweSPFrr2gTHvTdLKFAubTC53B25Fse+00fZHtfNmn2Qaw9bjyYUj8Lxqbk62bX683AQv1gTfq5zIZlhdym8DZk583RsdlYtX6UyNNFLmfRZAPLquyKjydxFaLYOERPrFwIxY+pu3sZ/Wb3ezg9bYZvNdc7jeNT49ZMGed69GV/yOemwgTnJUsE44AajQe7oD/taMGQIfSVWaqqx+/Xpafas3E//O9xRGK6+N3AhFP+fTZX3SLG9fHow91fZDatX781ugZfNHNyOJsVLQS4LDUkUElF8cV+EBlwVXLxuBWaMn5KFsOLUFJAgMBAAECggEARczG0+O4k5H/GGGyq+a8t5bpXGKNERFe+taqV2FdABqS2Rtbbe7vgIYXSRFkk0FLmjAzSnGaDIhgpilSySq/Qm+zzfoRLlMfO/HhXgRj4DvQfFiw/tdqo0a3ooe/f1uiY9D4jrnDRMYuHNj2QBSjURvrMP6xUwnyfSlNu4470hQwR2MhGCil85hcVr6DyBaDhNQ8XK0tfPA3TLie61Nsx7XwjeagW0C23RzL2Sj70BvEY3O8WUK/hQXVmnghB29uknpXGYlgBDh3E7tNfYIjgUhB5nV04Yx7oRLM6Cqk/MuKJ99PxOijlLtDkVScB4POJ6eAHBb0njxgEZxscQbn/QKBgQDoANEXBQ7JymOmiBg/fj4WYqmiAd2lLMf3ZXDjyyc8xcQSJJoeSQjKzIYABrTPDCur8eBzy93V1CsbZ9bhiQfcnj0tX+bLE3aKZ9EBG/7lYo9obY+d+lkoMMdMyw9xpWVYjlC7X8P4u5vk/BKPNfTPq3hAB5mTtacDrxRRKzuFswKBgQCxcJRLvu1Nce3yrpl9W8QFH1Agicg68+Cyhx3HsyigUeluPDzPq4BhON4dBxRiPK1Y2omb/JUOqDGbfDgTyOgYyO3xg1XmLHRW55GEhCXEFMnCKoToOKhRT8TueiiKFw03/3YX7MQuQOhBJffTAILRX/a1Y3+AJYfzt6gxHCPXEwKBgQDJXTwdkMQ/HKzVM7ZoFXhqEYROGvR3kqCU97S94evScYw2exJRSu6Ypl9/0lJIirW07aD0oHOQTjCD/uKgqkDqmWVb5qr4g5IVmvnqzpO0IJF7/+vxIAMWQRAadPyYlQebjxo/J2V+k8dBPhAVwK0VOiyK1o3TiIzHQ8SMlst4xQKBgDBfKm5DzFlSd7Wy13EPNS7YTHWyWf2IQnco0nuAYdDiw6ojjchnToYyhIqRRYNKW09ftCfsAY6PV4a1pGvwVyV6kTNHxIENGWIfmtHvXIRJzn66LKVJ3Mjd4CfK8YZDpnzfjYgUKZ8aXrZz7U1+VCtT5+OnDjkXAir0pEtPCo41AoGAHl0+8RtFXQyLEXmakzlqQYBS3UyY1TaqT+bU+Q2CaMAQYgsD524JIEkgV/RG2xET0xDCxDXD6eVO4Y1ZJOYwkWeB2AvXOEAaAJ7FUmi9fEcpOkWDGPWReCFDQR5zDsYm+v/0cihq+9FO+NabDgbguVLQuOoYXkO38397UA94Dho=
alipay.alipay-client.alipayPublicKey= MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwwbQIISof7d97gER63twSvcNwrFOKFISJ0u7SxTai1SNmSDJfETojz8fPUGn1qTqq+Q8fXtd0riKkPPFMXlTParRdEKwsPheCPxCbJtmMCY39cHA37wVOtygKJpqxJpKGYdTB7l+CjUyLUYLyzYPnIBqcDYyKj6FtM3dcsXaHaiWQR39Dcb736TZ+Q3qxrFzYv17RqrqpM8QiW5gRTjxmnIes6xdbUifMWKNnP3OK8ZF5w2S5xPgJy+5XQfjQV6gHpLVR8ov3f0HfMMlrhaGY9y3JDM/1fzzbU/yIt5uracBJpPpZPe280DbrCCQfzo+o0lrTXsf0bjhPAn4oJl1QwIDAQAB+Q8fXtd0riKkPPFMXlTParRdEKwsPheCPxCbJtmMCY39cHA37wVOtygKJpqxJpKGYdTB7l+CjUyLUYLyzYPnIBqcDYyKj6FtM3dcsXaHaiWQR39Dcb736TZ+Q3qxrFzYv17RqrqpM8QiW5gRTjxmnIes6xdbUifMWKNnP3OK8ZF5w2S5xPgJy+5XQfjQV6gHpLVR8ov3f0HfMMlrhaGY9y3JDM/1fzzbU/yIt5uracBJpPpZPe280DbrCCQfzo+o0lrTXsf0bjhPAn4oJl1QwIDAQAB
alipay.alipay-client.notifyUrl= http://ddns.myredstone.top:23333/alipay/notify
alipay.alipay-client.returnUrl= http://ddns.myredstone.top:23222/usercenter
alipay.alipay-client.encryptKey= qhWyJAnHL68D88FlpkF0JQ==
alipay.alipay-client.gatewayHost= https://openapi-sandbox.dl.alipaydev.com/gateway.do
alipay.alipay-client.format= json
alipay.alipay-client.charset= utf-8
alipay.alipay-client.signType= RSA2
alipay.alipay-client.encryptType= AES

# tomcat配置
server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.force-response=true