# 应用服务 WEB 访问端口
server.port=8080

# 数据库配置
spring.datasource.url=jdbc:mysql://localhost:3306/apartmentsystem?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=520134
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# mybatis-plus配置
mybatis-plus.mapper-locations=classpath:mappers/*.xml
mybatis-plus.configuration.map-underscore-to-camel-case=false
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# redis配置
spring.redis.host=localhost
spring.redis.port=6379

# alipay配置
alipay.alipay-client.appId= 
alipay.alipay-client.privateKey= 
alipay.alipay-client.alipayPublicKey= 
alipay.alipay-client.notifyUrl= 
alipay.alipay-client.returnUrl= 
alipay.alipay-client.encryptKey= 
alipay.alipay-client.gatewayHost= 
alipay.alipay-client.format= json
alipay.alipay-client.charset= utf-8
alipay.alipay-client.signType= RSA2
alipay.alipay-client.encryptType= AES

# tomcat配置
server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.force-response=true

# 文件上传配置
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.location= E:/apartSystemTemp/tmp/
custom.file.path= E:/apartSystemTemp/
custom.token= 1c17b11693cb5ec63859b091c5b9c1b2
custom.imageUrl= http://ddns.lyzd.fun:52333/api/index.php
